name: Checkout and run tests
description: Checkout test repo using GITHUB_PAT and run tests
runs:
  using: 'composite'
  steps:
    - name: Checkout tests
      shell: bash
      run: echo "GITHUB_PAT=$(aws ssm get-parameter --name /tio/github/access_token --with-decryption | jq -r .Parameter.Value)" >> $GITHUB_ENV
    - name: Checkout Service Configuration Repository
      uses: actions/checkout@v3
      with:
        repository: elsevier-health/esp-ui-automation-tests
        ref: develop
        token: ${{ env.GITHUB_PAT }}
    # Necessary to checkout back from the esp-configuration repo
    - name: Code checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      shell: bash
      run: npm ci
        
    - name: Install Playwright deps and browsers
      shell: bash
      run: npx playwright install --with-deps chromium
        
    - name: Run Playwright tests
      shell: bash
      run: npx playwright test --grep '@uismoke' --project=chromium

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
