name: CheckoutAndRun
on: 
  workflow_dispatch:
    inputs: 
      environment:
        description: Set 'dev', 'qa' or 'prod'
        required: true
        type: string
jobs:
  tests-run:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: philip-lu/playWrightTest
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install cross-env
        run: npm install --save-dev cross-env
      - name: Install Playwright deps and browsers
        run: npx playwright install --with-deps msedge
      - name: Run Playwright tests
        run: cross-env test_env=${{ inputs.environment }} npx playwright test --grep '@uismoke' --project='Microsoft Edge'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
