name: CheckoutAndRun
on: 
  workflow_dispatch:
    inputs: 
      environment:
        description: Set 'dev', 'qa' or 'prod'
        required: true
        type: string
jobs:
  tests-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ebooks_user1_pass: 'OhceAutoUser1!pass'
      test_env: ${{ inputs.environment }}
    steps:
    
      - uses: actions/checkout@main
        with:
          repository: philip-lu/playWrightTest
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright deps and browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests
        run: npx playwright test --grep '@nrt'
        
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: monocart-results
          path: monocart-results/
          retention-days: 30
      


      - name: Checkout to gh-pages
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        if: always()
        id: test-report
        with:
          test_results: monocart-results
          gh_pages: gh-pages

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: monocart-results

 
